import { bagelFatOne, googleSans, grotesk, TTBlueScreens } from '@/font';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'PKL SMKN 3 KEDIRI',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body
                className={`${googleSans.className} ${grotesk.variable} ${TTBlueScreens.variable} ${bagelFatOne.variable} text-zinc-800 bg-primary-50 antialiased`}>
                {children}
            </body>
        </html>
    );
}
